
  filebeat.inputs:
-  type: filestream
   id: my-filestream-id
   enabled: true
   paths:
    - { { log_file } }

   filebeat.config.modules:
     path: ${path.config}/modules.d/*.yml
     reload.enabled: false
   setup.template.settings:
     index.number_of_shards: 1

   output.logstash:
   hosts: ["172.31.26.246:5044"]
  ##defaults
   processors:
    - add_host_metadata:
      when.not.contains.tags: forwarded
    - add_cloud_metadata: ~
    - add_docker_metadata: ~
    - add_kubernetes_metadata: ~

