- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy roboshop config file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: clean old content
  ansible.builtin.file:
   path: /usr/share/nginx/html
   state: absent

   name: Create app directory
   ansible.builtin.file:
     path: /usr/share/nginx/html
     state: directory




