- name: copy prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
#    src: "{{item}}.yml"
    dest: /opt/prometheus/prometheus.yml
#  loop:
#      - prometheus
#      - alerts

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes

#- name: check if prometheus is running or not
#  ansible.builtin.shell: sleep 10 ; netstat -lntp | grep 9090


#- name: wait for prometheus started or not
 # ansible.builtin.wait_for:
  #  port: 9090
   # delay: 10
    #timeout: 15m

