
- name: create application user
  ansible.builtin.user:
    name: "{{app_user}}"

- name: clean old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create application directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download application content
  ansible.builtin.unarchive:
    #src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    src:
    dest: /app
    remote_src: yes