- name: install python
  ansible.builtin.yum:
    name:
     - python36
     - gcc
     - python3-devel

- name: include app_prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: install python dependencies
  ansible.buitin.shell: pip3.6 install -r requirements.txt
  arges:
    chdir: /app

- name: include schema setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: include SystemD
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
