- name: Load MongoDB Schema
  when: schema_setup == "mongo"
  block:
    - name: Copy MongoDB  repo file
      ansible.builtin.copy:
       src: mongodb.repo
       dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed


    - name: Load Schema
      ansible.builtin.shell: mongo --ssl --host {{ lookup('aws_ssm', "{{env}}.docdb.DOCDB_URL", region='us-east-1' ) }}:27017 --sslCAFile /app/rds-combined-ca-bundle.pem --username {{ lookup('aws_ssm', "{{env}}.docdb.DB_ADMIN_USER", region='us-east-1' ) }} --password {{ lookup('aws_ssm', "{{env}}.docdb.DB_ADMIN_PASS", region='us-east-1' ) }} < /app/schema/{{component}}.js




- name: Load MYSQL Schema
  when: schema_setup == "mysql"
  block:
     - name: install MYSQL client
       ansible.builtin.yum:
         name: mysql

     - name: Load Schema
