groups:
  - name: ec2-nodes
    rules:
      - alert: HighCPUUtilization
        expr: 100- (avg by (component, env, instance, job, name) (rate(node_cpu_seconds_total{mode="idle"}[1m]) * 100)) > 50
        for: 1m
        labels:
          severity: page
        annotations:
          summary: High CPU usage

      - alert: HighMemoryUtilization
        expr: 100 - (100 * ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes ) / node_memory_MemTotal_bytes))
        for: 1m
        labels:
          severity: page
        annotations:
          summary: High Memory Usage

      - alert: ServerDown
        expr: up < 1
        for: 1m
        labels:
          severity: page
        annotations:
           summary: server Down

      {% for component in components %}
      - alert: ServiceDown
        expr: node_systemd_unit_state{component="{{ component.name }}", exported_name="{{ component.service_name }}.service", state="active"}
        for: 1m
        labels:
          severity: page
        annotations:
          summary: Server Down {{ component.name }} Component - service down
      {% endfor %}